"""Seed a curated question bank so gameplay never depends on live LLM calls."""

from __future__ import annotations

from hashlib import sha256

from sqlalchemy import func, select

from app.core.database import session_scope
from app.core.languages import DEFAULT_LANGUAGE, ContentLanguage
from app.core.logging import get_logger
from app.models import DifficultyLabel, Question, QuestionOption, QuestionStatus, Topic

logger = get_logger(__name__)

# (topic_slug, difficulty_label, difficulty_float, prompt, options[4], correct_index, explanation)
BANK: list[tuple] = [
    # Astronomy
    ("astronomy", "medium", 0.55, "Which planet rotates the fastest?",
     ["Earth", "Jupiter", "Saturn", "Neptune"], 1,
     "Jupiter completes one rotation in roughly 10 hours, making it the fastest rotating planet."),
    ("astronomy", "easy", 0.3, "What is the closest star to Earth?",
     ["Proxima Centauri", "Sirius", "The Sun", "Alpha Centauri A"], 2,
     "The Sun is the star at the center of our solar system and is by far the closest to Earth."),
    ("astronomy", "medium", 0.5, "What is a light-year a measure of?",
     ["Time", "Distance", "Brightness", "Mass"], 1,
     "A light-year is the distance light travels in one year — about 9.46 trillion kilometers."),
    ("astronomy", "hard", 0.75, "What is the event horizon of a black hole?",
     ["The accretion disk", "The boundary beyond which nothing can escape", "The singularity", "The photon sphere"], 1,
     "The event horizon is the surface of no return around a black hole."),
    ("astronomy", "easy", 0.25, "How many planets are in our solar system?",
     ["7", "8", "9", "10"], 1,
     "There are eight recognized planets since Pluto was reclassified as a dwarf planet."),
    ("astronomy", "medium", 0.6, "Which moon is the largest in the solar system?",
     ["Titan", "Europa", "Ganymede", "Callisto"], 2,
     "Ganymede, a moon of Jupiter, is larger than Mercury."),
    ("astronomy", "hard", 0.8, "What primarily powers the Sun's energy output?",
     ["Chemical burning", "Gravitational collapse", "Nuclear fission", "Nuclear fusion"], 3,
     "Hydrogen nuclei fuse into helium in the Sun's core, releasing enormous energy."),
    ("astronomy", "expert", 0.9, "Approximately what is the Schwarzschild radius formula for a non-rotating black hole?",
     ["R = 2GM/c²", "R = GM/c²", "R = 2GM/c", "R = GM/c"], 0,
     "The Schwarzschild radius is R_s = 2GM/c²."),
    ("astronomy", "easy", 0.28, "What galaxy does our solar system belong to?",
     ["Andromeda", "Milky Way", "Triangulum", "Sombrero"], 1,
     "The Sun and its planets orbit within the Milky Way galaxy."),
    ("astronomy", "medium", 0.52, "What causes a total solar eclipse?",
     ["Earth blocks the Moon", "The Moon passes between Earth and the Sun", "The Sun passes behind Earth", "Mars aligns with the Sun"], 1,
     "A solar eclipse occurs when the Moon's shadow falls on Earth as it crosses in front of the Sun."),
    ("astronomy", "hard", 0.72, "What does cosmological redshift primarily indicate?",
     ["Stars are cooling", "Galaxies are moving away from us", "Light is slowing down", "Dust is absorbing blue light"], 1,
     "Redshift of distant galaxies shows they are receding, evidence of cosmic expansion."),
    ("astronomy", "medium", 0.58, "Which planet is hottest despite not being closest to the Sun?",
     ["Mercury", "Venus", "Mars", "Jupiter"], 1,
     "Venus's thick carbon dioxide atmosphere traps heat, making it hotter than Mercury."),

    # Science
    ("science", "easy", 0.3, "What gas do plants absorb during photosynthesis?",
     ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], 2,
     "Plants take in carbon dioxide and release oxygen during photosynthesis."),
    ("science", "medium", 0.5, "What is the chemical symbol for gold?",
     ["Go", "Gd", "Au", "Ag"], 2,
     "Au comes from the Latin word aurum."),
    ("science", "easy", 0.25, "At sea level, water boils at what temperature in Celsius?",
     ["90°C", "100°C", "110°C", "120°C"], 1,
     "At standard atmospheric pressure, water boils at 100°C."),
    ("science", "easy", 0.3, "What is the hardest naturally occurring substance on Earth?",
     ["Quartz", "Diamond", "Graphite", "Topaz"], 1,
     "Diamond's carbon atoms form a rigid crystal lattice, giving it extreme hardness."),
    ("science", "medium", 0.55, "Newton's first law of motion describes:",
     ["Action and reaction", "Inertia", "Gravitational attraction", "Conservation of energy"], 1,
     "The first law states that objects resist changes in their state of motion."),
    ("science", "medium", 0.52, "The ozone layer in the atmosphere primarily absorbs:",
     ["Infrared radiation", "Ultraviolet radiation", "Radio waves", "X-rays"], 1,
     "Ozone molecules absorb harmful UV radiation before it reaches Earth's surface."),
    ("science", "hard", 0.75, "Which subatomic particle carries a negative electric charge?",
     ["Proton", "Neutron", "Electron", "Positron"], 2,
     "Electrons orbit the nucleus and have a charge of −1 elementary charge."),
    ("science", "hard", 0.78, "What does a catalyst do in a chemical reaction?",
     ["Increases product mass", "Speeds the reaction without being consumed", "Changes the products formed", "Stops the reaction"], 1,
     "Catalysts lower activation energy and are regenerated at the end of the reaction."),
    ("science", "expert", 0.88, "Avogadro's number is approximately:",
     ["6.02 × 10²³", "3.14 × 10⁸", "9.81 × 10²", "1.60 × 10⁻¹⁹"], 0,
     "One mole of any substance contains about 6.02 × 10²³ particles."),
    ("science", "easy", 0.28, "Which state of matter has neither fixed shape nor volume?",
     ["Solid", "Liquid", "Gas", "Plasma"], 2,
     "Gas particles move freely and fill any container they occupy."),
    ("science", "medium", 0.5, "Sound travels fastest through which medium?",
     ["Air", "Water", "Steel", "Vacuum"], 2,
     "Sound is a mechanical wave and propagates faster in denser, stiffer materials like steel."),
    ("science", "hard", 0.72, "Entropy in thermodynamics measures:",
     ["Total energy", "Disorder or randomness of a system", "Temperature change", "Pressure volume ratio"], 1,
     "Entropy quantifies how dispersed energy is within a system."),

    # Physics
    ("physics", "medium", 0.55, "What is the SI unit of force?",
     ["Joule", "Watt", "Newton", "Pascal"], 2,
     "Force is measured in newtons (N)."),
    ("physics", "hard", 0.78, "In vacuum, the speed of light is approximately:",
     ["3×10⁵ m/s", "3×10⁶ m/s", "3×10⁷ m/s", "3×10⁸ m/s"], 3,
     "c ≈ 299,792,458 m/s, commonly approximated as 3×10⁸ m/s."),
    ("physics", "easy", 0.28, "What is the SI unit of electric current?",
     ["Volt", "Ohm", "Ampere", "Watt"], 2,
     "Current is measured in amperes (A), defined as one coulomb per second."),
    ("physics", "easy", 0.3, "Near Earth's surface, gravitational acceleration is approximately:",
     ["1.6 m/s²", "5.0 m/s²", "9.8 m/s²", "15 m/s²"], 2,
     "Objects in free fall near Earth's surface accelerate at about 9.8 m/s²."),
    ("physics", "medium", 0.5, "When light enters water from air, it bends due to:",
     ["Reflection", "Refraction", "Diffraction", "Polarization"], 1,
     "Refraction occurs because light changes speed when crossing media boundaries."),
    ("physics", "medium", 0.55, "The Doppler effect explains the change in:",
     ["Mass of moving objects", "Frequency of waves from a moving source", "Chemical composition", "Magnetic field strength"], 1,
     "A moving source compresses or stretches wavefronts, shifting observed frequency."),
    ("physics", "hard", 0.75, "The Heisenberg uncertainty principle states that:",
     ["Energy is always conserved", "Position and momentum cannot both be precisely known", "Light is only a particle", "Gravity is a force only"], 1,
     "Quantum mechanics limits simultaneous precision of complementary variables."),
    ("physics", "hard", 0.78, "In an isolated system, total momentum is:",
     ["Always increasing", "Always decreasing", "Conserved", "Zero"], 2,
     "Momentum conservation holds when no external forces act on the system."),
    ("physics", "expert", 0.9, "The Planck constant h has units of:",
     ["Joule", "Joule-second", "Watt", "Newton-meter"], 1,
     "Planck's constant relates energy to frequency: E = hf."),
    ("physics", "easy", 0.25, "Electrical potential difference is measured in:",
     ["Amperes", "Volts", "Ohms", "Coulombs"], 1,
     "Voltage (potential difference) is measured in volts (V)."),
    ("physics", "medium", 0.52, "Kinetic energy depends on:",
     ["Mass and velocity", "Mass and height", "Volume and pressure", "Charge and distance"], 0,
     "Kinetic energy is KE = ½mv², depending on mass and speed."),
    ("physics", "hard", 0.72, "Wavelength and frequency of a wave are related by:",
     ["λ = v/f", "λ = f/v", "λ = v × f", "λ = f²/v"], 0,
     "Wave speed equals frequency times wavelength: v = fλ."),

    # Chemistry
    ("chemistry", "easy", 0.28, "What is the atomic number of hydrogen?",
     ["0", "1", "2", "8"], 1,
     "Hydrogen has one proton, so its atomic number is 1."),
    ("chemistry", "medium", 0.52, "pH 7 is considered:",
     ["Acidic", "Basic", "Neutral", "Alkaline only"], 2,
     "A pH of 7 is neutral on the pH scale."),
    ("chemistry", "easy", 0.25, "What is the chemical symbol for sodium?",
     ["So", "Sd", "Na", "No"], 2,
     "Na comes from the Latin name natrium."),
    ("chemistry", "easy", 0.3, "Carbon dioxide has the chemical formula:",
     ["CO", "CO₂", "C₂O", "CH₄"], 1,
     "CO₂ consists of one carbon atom bonded to two oxygen atoms."),
    ("chemistry", "medium", 0.5, "Noble gases belong to which group of the periodic table?",
     ["Group 1", "Group 8", "Group 18", "Group 17"], 2,
     "Group 18 elements have full outer electron shells and are largely unreactive."),
    ("chemistry", "medium", 0.55, "Rusting of iron is primarily an example of:",
     ["Evaporation", "Oxidation", "Sublimation", "Distillation"], 1,
     "Iron reacts with oxygen and moisture, forming iron oxide."),
    ("chemistry", "hard", 0.75, "In a covalent bond, electrons are:",
     ["Transferred completely to one atom", "Shared between atoms", "Removed from all atoms", "Only in the nucleus"], 1,
     "Covalent bonds form when atoms share electron pairs."),
    ("chemistry", "hard", 0.78, "Horizontal rows in the periodic table are called:",
     ["Groups", "Periods", "Isotopes", "Allotropes"], 1,
     "Periods are horizontal rows; elements in a period share the same number of electron shells."),
    ("chemistry", "expert", 0.88, "Le Chatelier's principle predicts how a system at equilibrium responds to:",
     ["Only temperature increases", "Changes in concentration, pressure, or temperature", "Only pressure decreases", "Magnetic fields"], 1,
     "Equilibrium shifts to partially counteract imposed changes."),
    ("chemistry", "easy", 0.28, "A solution with pH 3 is:",
     ["Neutral", "Acidic", "Basic", "Salt"], 1,
     "Values below 7 on the pH scale indicate acidity."),
    ("chemistry", "medium", 0.52, "The mole is a unit that measures:",
     ["Volume of gas", "Amount of substance", "Reaction speed", "Bond strength"], 1,
     "One mole contains Avogadro's number of particles."),
    ("chemistry", "hard", 0.72, "An ionic bond typically forms between:",
     ["Two nonmetals", "A metal and a nonmetal", "Two metals", "Two noble gases"], 1,
     "Metals donate electrons to nonmetals, creating charged ions that attract."),

    # Biology
    ("biology", "easy", 0.3, "What is the powerhouse of the cell?",
     ["Nucleus", "Ribosome", "Mitochondrion", "Golgi apparatus"], 2,
     "Mitochondria generate most of the cell's ATP."),
    ("biology", "medium", 0.55, "DNA is primarily stored in which organelle of eukaryotic cells?",
     ["Ribosome", "Nucleus", "Lysosome", "Vacuole"], 1,
     "Most DNA in eukaryotes is housed in the nucleus."),
    ("biology", "easy", 0.28, "What is the largest organ of the human body?",
     ["Liver", "Brain", "Skin", "Lungs"], 2,
     "The skin covers the entire body and is the largest organ by surface area."),
    ("biology", "easy", 0.3, "Photosynthesis in plants primarily produces:",
     ["Carbon dioxide", "Nitrogen", "Oxygen", "Methane"], 2,
     "Plants release oxygen as a byproduct of splitting water during photosynthesis."),
    ("biology", "medium", 0.5, "The double helix structure of DNA was described by:",
     ["Darwin and Wallace", "Watson and Crick", "Pasteur and Koch", "Mendel and Morgan"], 1,
     "James Watson and Francis Crick proposed the DNA double helix in 1953."),
    ("biology", "medium", 0.55, "Natural selection is most closely associated with:",
     ["Charles Darwin", "Louis Pasteur", "Gregor Mendel", "Marie Curie"], 0,
     "Darwin explained how species adapt through differential survival of traits."),
    ("biology", "hard", 0.75, "Enzymes in biological systems act as:",
     ["Energy sources", "Biological catalysts", "Structural fibers", "Genetic material"], 1,
     "Enzymes speed biochemical reactions by lowering activation energy."),
    ("biology", "hard", 0.78, "The central dogma of molecular biology describes flow from:",
     ["Protein to DNA", "DNA to RNA to protein", "RNA to lipid", "Carbohydrate to DNA"], 1,
     "Genetic information is transcribed to RNA and translated into proteins."),
    ("biology", "expert", 0.9, "Mitochondrial DNA is inherited primarily from:",
     ["The father", "The mother", "Both parents equally", "Neither parent"], 1,
     "Mitochondria in offspring usually come from the egg cell, carrying maternal mtDNA."),
    ("biology", "easy", 0.25, "Organisms that make their own food are called:",
     ["Heterotrophs", "Autotrophs", "Decomposers", "Parasites"], 1,
     "Autotrophs such as plants produce organic matter from inorganic sources."),
    ("biology", "medium", 0.52, "Vaccines work by stimulating:",
     ["Immediate pathogen destruction", "Immune memory against pathogens", "Cell division in bones", "Digestive enzyme production"], 1,
     "Vaccines train the immune system to recognize and fight specific pathogens."),
    ("biology", "hard", 0.72, "Homologous structures in different species suggest:",
     ["Convergent evolution", "Common ancestry", "Random mutation only", "No evolutionary relationship"], 1,
     "Similar underlying structure despite different function indicates shared evolutionary origin."),

    # Mathematics
    ("mathematics", "easy", 0.25, "What is 12 × 8?",
     ["86", "96", "106", "88"], 1, "12 × 8 = 96."),
    ("mathematics", "medium", 0.5, "What is the derivative of x²?",
     ["x", "2x", "x²", "2"], 1, "d/dx(x²) = 2x."),
    ("mathematics", "hard", 0.75, "What is the next prime after 29?",
     ["30", "31", "33", "35"], 1, "31 is the next prime number after 29."),
    ("mathematics", "medium", 0.55, "What is the value of π (pi) approximately?",
     ["2.14", "3.14", "3.41", "4.13"], 1, "π ≈ 3.14159…"),
    ("mathematics", "expert", 0.88, "The integral of 1/x dx is:",
     ["x²/2 + C", "ln|x| + C", "1/x² + C", "e^x + C"], 1,
     "The antiderivative of 1/x is the natural logarithm of |x|."),
    ("mathematics", "easy", 0.28, "What is 15 + 27?",
     ["40", "41", "42", "43"], 2, "15 + 27 = 42."),
    ("mathematics", "easy", 0.3, "What is 7 squared (7²)?",
     ["14", "49", "56", "64"], 1, "7² = 7 × 7 = 49."),
    ("mathematics", "medium", 0.52, "The area of a circle with radius r is:",
     ["2πr", "πr²", "πd", "r²"], 1, "Circle area A = πr²."),
    ("mathematics", "medium", 0.55, "In the Pythagorean theorem, a² + b² equals:",
     ["c", "c²", "2c", "c³"], 1, "For a right triangle, a² + b² = c² where c is the hypotenuse."),
    ("mathematics", "hard", 0.75, "The derivative of sin(x) is:",
     ["−cos(x)", "cos(x)", "sin(x)", "tan(x)"], 1, "d/dx[sin(x)] = cos(x)."),
    ("mathematics", "hard", 0.78, "What is the slope of a horizontal line?",
     ["0", "1", "Undefined", "Infinity"], 0, "A horizontal line has no vertical change, so slope m = 0."),
    ("mathematics", "expert", 0.92, "Euler's identity states that e^(iπ) + 1 equals:",
     ["0", "1", "i", "π"], 0, "Euler's formula gives e^(iπ) = −1, so e^(iπ) + 1 = 0."),

    # Artificial Intelligence
    ("artificial-intelligence", "easy", 0.3, "What does AI stand for?",
     ["Automated Interface", "Artificial Intelligence", "Applied Informatics", "Advanced Integration"], 1,
     "AI stands for Artificial Intelligence."),
    ("artificial-intelligence", "medium", 0.55, "Which technique is commonly used to train deep neural networks?",
     ["Bubble sort", "Backpropagation", "Binary search", "Round-robin"], 1,
     "Backpropagation adjusts weights based on the loss gradient."),
    ("artificial-intelligence", "hard", 0.8, "In transformers, what does self-attention primarily compute?",
     ["Only positional encodings", "Relationships between tokens in a sequence", "GPU memory maps", "Dataset checksums"], 1,
     "Self-attention weighs how each token relates to others in the sequence."),
    ("artificial-intelligence", "easy", 0.28, "Machine learning is best described as:",
     ["A branch of AI that learns from data", "A type of computer hardware", "A programming language", "A database protocol"], 0,
     "ML systems improve performance by learning patterns from data."),
    ("artificial-intelligence", "medium", 0.5, "Overfitting occurs when a model:",
     ["Performs well on training data but poorly on new data", "Never learns patterns", "Uses too little data always", "Has no parameters"], 0,
     "Overfit models memorize training noise instead of generalizable patterns."),
    ("artificial-intelligence", "medium", 0.55, "Convolutional Neural Networks (CNNs) are especially suited for:",
     ["Spreadsheet calculations", "Image recognition", "Sorting algorithms", "File compression"], 1,
     "CNNs use convolutional filters to detect spatial features in images."),
    ("artificial-intelligence", "hard", 0.75, "Gradient descent is used to:",
     ["Minimize a loss function by updating parameters", "Increase dataset size", "Encrypt model weights", "Compile source code"], 0,
     "Parameters are adjusted in the direction that reduces the loss."),
    ("artificial-intelligence", "hard", 0.78, "In reinforcement learning, an agent learns by:",
     ["Copying labeled examples only", "Receiving rewards and penalties from actions", "Reading static documentation", "Random weight initialization only"], 1,
     "RL agents optimize policies through trial-and-error feedback signals."),
    ("artificial-intelligence", "expert", 0.9, "The attention mechanism in transformers allows models to:",
     ["Ignore all context", "Focus on relevant parts of the input sequence", "Run without parameters", "Eliminate the need for data"], 1,
     "Attention weights let models dynamically emphasize important tokens."),
    ("artificial-intelligence", "easy", 0.3, "Training data is used to:",
     ["Test final model accuracy only", "Teach the model patterns during learning", "Store user passwords", "Configure network routers"], 1,
     "Models learn parameters by fitting patterns in training data."),
    ("artificial-intelligence", "medium", 0.52, "NLP stands for:",
     ["Neural Logic Processing", "Natural Language Processing", "Network Layer Protocol", "Numeric Linear Programming"], 1,
     "NLP enables computers to understand and generate human language."),
    ("artificial-intelligence", "hard", 0.72, "A Generative Adversarial Network (GAN) consists of:",
     ["Two generators", "A generator and a discriminator", "Three classifiers", "A single regression tree"], 1,
     "The generator creates samples while the discriminator judges their realism."),

    # Programming
    ("programming", "easy", 0.28, "Which symbol starts a single-line comment in Python?",
     ["//", "/*", "#", "--"], 2, "Python uses # for single-line comments."),
    ("programming", "medium", 0.5, "What does HTTP status 404 mean?",
     ["OK", "Unauthorized", "Not Found", "Server Error"], 2,
     "404 indicates the requested resource was not found."),
    ("programming", "hard", 0.78, "Big-O of binary search on a sorted array is:",
     ["O(n)", "O(log n)", "O(n log n)", "O(1)"], 1,
     "Binary search halves the search space each step: O(log n)."),
    ("programming", "easy", 0.25, "HTML is primarily used for:",
     ["Styling web pages", "Structuring web content", "Compiling code", "Managing databases"], 1,
     "HTML defines the structure and content of web documents."),
    ("programming", "easy", 0.3, "A variable in programming is used to:",
     ["Delete files permanently", "Store data that can change", "Shut down the computer", "Encrypt the hard drive"], 1,
     "Variables hold values that programs can read and modify during execution."),
    ("programming", "medium", 0.52, "Git is primarily used for:",
     ["Image editing", "Version control", "Video streaming", "Spreadsheet formulas"], 1,
     "Git tracks code changes and enables collaboration through branching and merging."),
    ("programming", "medium", 0.55, "Recursion occurs when a function:",
     ["Never returns", "Calls itself", "Deletes its own code", "Runs only once"], 1,
     "Recursive functions solve problems by invoking themselves on smaller subproblems."),
    ("programming", "hard", 0.75, "A deadlock in concurrent programming happens when:",
     ["A program runs too fast", "Threads wait forever for each other to release resources", "Memory is unlimited", "All threads finish instantly"], 1,
     "Deadlock arises when circular resource dependencies prevent any thread from proceeding."),
    ("programming", "hard", 0.78, "REST APIs typically use HTTP methods such as:",
     ["GET and POST", "PRINT and SCAN", "BOOT and HALT", "PING and TRACE only"], 0,
     "RESTful services use standard HTTP verbs like GET, POST, PUT, and DELETE."),
    ("programming", "expert", 0.9, "The CAP theorem states that a distributed system cannot simultaneously guarantee:",
     ["Speed, size, and cost", "Consistency, availability, and partition tolerance all fully", "Input, output, and storage", "Compile, link, and run"], 1,
     "Under network partitions, systems must choose between consistency and availability."),
    ("programming", "medium", 0.5, "Compiled languages differ from interpreted languages because compiled code is:",
     ["Never executed", "Translated to machine code before running", "Only run in browsers", "Always slower"], 1,
     "Compilers translate source code into executable machine instructions ahead of time."),
    ("programming", "hard", 0.72, "Garbage collection in managed runtimes automatically:",
     ["Deletes source files", "Reclaims memory no longer referenced", "Compiles code faster", "Encrypts variables"], 1,
     "GC identifies unreachable objects and frees their memory for reuse."),

    # Technology
    ("technology", "easy", 0.3, "What does CPU stand for?",
     ["Central Processing Unit", "Computer Personal Unit", "Central Program Utility", "Core Power Unit"], 0,
     "CPU means Central Processing Unit."),
    ("technology", "medium", 0.55, "Which protocol is primarily used to securely browse websites?",
     ["FTP", "SMTP", "HTTPS", "SSH"], 2,
     "HTTPS is HTTP secured with TLS."),
    ("technology", "easy", 0.28, "RAM is used to:",
     ["Store data permanently", "Provide fast temporary memory", "Cool the processor", "Connect to satellites"], 1,
     "RAM holds data and instructions the CPU needs while programs are running."),
    ("technology", "easy", 0.3, "An SSD stores data on:",
     ["Magnetic spinning disks", "Flash memory chips", "Punch cards", "Optical tape only"], 1,
     "Solid-state drives use flash memory with no mechanical moving parts."),
    ("technology", "medium", 0.5, "DNS (Domain Name System) translates:",
     ["IP addresses to MAC addresses", "Domain names to IP addresses", "Files to folders", "Emails to phone numbers"], 1,
     "DNS resolves human-readable domain names into numeric IP addresses."),
    ("technology", "medium", 0.55, "Bluetooth is a technology for:",
     ["Wired high-speed networking", "Short-range wireless communication", "Satellite navigation", "Nuclear power generation"], 1,
     "Bluetooth enables low-power wireless links between nearby devices."),
    ("technology", "hard", 0.75, "Moore's Law originally observed that:",
     ["Battery life doubles yearly", "Transistor counts on chips roughly double every two years", "Internet speed is constant", "Software never grows in size"], 1,
     "Moore predicted rapid growth in computing power through miniaturization."),
    ("technology", "hard", 0.78, "A firewall in networking is designed to:",
     ["Speed up downloads", "Monitor and control incoming and outgoing traffic", "Increase screen resolution", "Store backup files"], 1,
     "Firewalls enforce security rules to block unauthorized network access."),
    ("technology", "expert", 0.88, "Quantum computers use qubits, which can represent:",
     ["Only 0 or 1 at a time", "Superpositions of 0 and 1", "Only negative values", "Analog voltages only"], 1,
     "Qubits exploit quantum superposition to perform certain computations faster."),
    ("technology", "easy", 0.25, "Wi-Fi enables devices to connect:",
     ["Only via cables", "Wirelessly to a network", "Only to printers", "Only to keyboards"], 1,
     "Wi-Fi uses radio waves for wireless local area networking."),
    ("technology", "medium", 0.52, "Cloud computing delivers services over:",
     ["Floppy disks only", "The internet from remote servers", "Local punch cards", "Manual mail delivery"], 1,
     "Cloud providers host compute, storage, and apps accessible on demand online."),
    ("technology", "hard", 0.72, "Blockchain technology is characterized by:",
     ["Centralized single-server storage", "A distributed ledger of linked records", "Analog signal transmission", "One-time-use memory chips"], 1,
     "Blockchains store tamper-resistant records across a distributed network."),

    # History
    ("history", "easy", 0.3, "In which year did World War II end?",
     ["1918", "1939", "1945", "1963"], 2, "World War II ended in 1945."),
    ("history", "medium", 0.55, "Who was the first President of the United States?",
     ["Thomas Jefferson", "John Adams", "George Washington", "Abraham Lincoln"], 2,
     "George Washington served as the first U.S. President."),
    ("history", "easy", 0.28, "The United States Declaration of Independence was adopted in:",
     ["1492", "1776", "1865", "1914"], 1,
     "The Continental Congress adopted the Declaration on July 4, 1776."),
    ("history", "easy", 0.3, "The capital of the ancient Roman Empire was:",
     ["Athens", "Rome", "Cairo", "Babylon"], 1,
     "Rome was the political and cultural center of the Roman Empire."),
    ("history", "medium", 0.5, "The Berlin Wall fell in which year?",
     ["1961", "1979", "1989", "2001"], 2,
     "The Berlin Wall was opened and dismantled in 1989, symbolizing the end of the Cold War era."),
    ("history", "medium", 0.55, "The French Revolution began in:",
     ["1689", "1789", "1889", "1989"], 1,
     "Revolutionary upheaval in France began in 1789 with the storming of the Bastille."),
    ("history", "hard", 0.75, "The Magna Carta, signed in 1215, limited the power of:",
     ["The Pope", "The English king", "Parliament only", "Colonial governors"], 1,
     "The Magna Carta established that the monarch was subject to the law."),
    ("history", "hard", 0.78, "The Renaissance cultural movement began primarily in:",
     ["Northern Europe in the 10th century", "Italy in the 14th century", "South America in the 18th century", "Japan in the 12th century"], 1,
     "The Renaissance emerged in Italy before spreading across Europe."),
    ("history", "expert", 0.9, "The Treaty of Versailles (1919) formally ended:",
     ["World War II", "World War I", "The Napoleonic Wars", "The Cold War"], 1,
     "The treaty imposed peace terms on Germany after World War I."),
    ("history", "medium", 0.52, "The Cold War was primarily a geopolitical rivalry between:",
     ["France and Germany", "USA and USSR", "China and Japan", "Brazil and Argentina"], 1,
     "The US and Soviet Union competed for global influence from the late 1940s to 1991."),
    ("history", "hard", 0.72, "Christopher Columbus's 1492 voyage was sponsored by:",
     ["England", "Spain", "Portugal", "France"], 1,
     "Queen Isabella and King Ferdinand of Spain funded Columbus's Atlantic expedition."),
    ("history", "hard", 0.75, "The Mughal Empire was a major power in:",
     ["Medieval Japan", "South Asia (India)", "Scandinavia", "West Africa"], 1,
     "The Mughal Empire ruled large parts of the Indian subcontinent from the 16th to 19th centuries."),

    # Geography
    ("geography", "easy", 0.28, "What is the largest ocean on Earth?",
     ["Atlantic", "Indian", "Arctic", "Pacific"], 3,
     "The Pacific Ocean is the largest."),
    ("geography", "medium", 0.5, "Which country has the most time zones?",
     ["USA", "Russia", "France", "China"], 2,
     "France has the most time zones due to its overseas territories."),
    ("geography", "hard", 0.75, "What is the capital of Australia?",
     ["Sydney", "Melbourne", "Canberra", "Perth"], 2,
     "Canberra is the capital city of Australia."),
    ("geography", "easy", 0.25, "Mount Everest is located in the:",
     ["Andes", "Himalayas", "Alps", "Rockies"], 1,
     "Everest sits in the Himalayas on the Nepal–China border."),
    ("geography", "easy", 0.3, "The capital of Japan is:",
     ["Osaka", "Kyoto", "Tokyo", "Hiroshima"], 2,
     "Tokyo is Japan's capital and largest city."),
    ("geography", "medium", 0.52, "The Sahara is the largest:",
     ["Rainforest", "Hot desert", "Island", "Lake"], 1,
     "The Sahara in North Africa is the world's largest hot desert."),
    ("geography", "medium", 0.55, "The Amazon rainforest is located primarily in:",
     ["Africa", "South America", "Australia", "Europe"], 1,
     "Most of the Amazon basin lies within Brazil and neighboring South American countries."),
    ("geography", "hard", 0.75, "The Ring of Fire is associated with:",
     ["Arctic ice melt", "Pacific Ocean earthquakes and volcanoes", "Sahara sandstorms", "Mediterranean trade routes"], 1,
     "The Ring of Fire encircles the Pacific with intense seismic and volcanic activity."),
    ("geography", "hard", 0.78, "The equator is located at latitude:",
     ["90°", "45°", "0°", "180°"], 2,
     "The equator is the 0° latitude line dividing Earth into northern and southern hemispheres."),
    ("geography", "expert", 0.88, "Tectonic plates move due to forces in:",
     ["Earth's atmosphere", "Earth's mantle and lithosphere", "The Moon's gravity only", "Ocean surface waves"], 1,
     "Convection in the mantle drives plate motion at boundaries."),
    ("geography", "easy", 0.28, "The Nile River flows primarily through:",
     ["South America", "Africa", "Europe", "Australia"], 1,
     "The Nile runs northward through northeastern Africa to the Mediterranean."),
    ("geography", "medium", 0.5, "The Great Barrier Reef is off the coast of:",
     ["India", "Australia", "Mexico", "Norway"], 1,
     "The Great Barrier Reef lies in the Coral Sea along Australia's northeast coast."),

    # Psychology
    ("psychology", "medium", 0.5, "Who proposed the hierarchy of needs?",
     ["Freud", "Jung", "Maslow", "Pavlov"], 2,
     "Abraham Maslow proposed the hierarchy of needs."),
    ("psychology", "easy", 0.28, "Ivan Pavlov is famous for experiments on:",
     ["Classical conditioning", "Dream analysis", "IQ testing", "Color perception"], 0,
     "Pavlov demonstrated classical conditioning using dogs and salivation responses."),
    ("psychology", "easy", 0.3, "The placebo effect occurs when:",
     ["A treatment has no ingredients but patients still improve", "Medicine always fails", "Patients refuse treatment", "Symptoms worsen from rest"], 0,
     "Expectations and context can produce real physiological changes without active medication."),
    ("psychology", "medium", 0.52, "Cognitive dissonance refers to:",
     ["Perfect memory recall", "Mental discomfort from conflicting beliefs", "Enhanced athletic performance", "Sleep paralysis"], 1,
     "People feel tension when holding contradictory attitudes or behaviors."),
    ("psychology", "medium", 0.55, "Operant conditioning was developed primarily by:",
     ["B.F. Skinner", "Sigmund Freud", "Carl Jung", "William James"], 0,
     "Skinner studied how consequences shape voluntary behavior."),
    ("psychology", "hard", 0.75, "The amygdala is strongly linked to processing:",
     ["Digestion", "Fear and emotional responses", "Balance and hearing", "Color vision"], 1,
     "The amygdala plays a key role in threat detection and emotional memory."),
    ("psychology", "hard", 0.78, "Attachment theory in developmental psychology is associated with:",
     ["John Bowlby", "Albert Einstein", "Isaac Newton", "Charles Babbage"], 0,
     "Bowlby emphasized the importance of early bonds with caregivers."),
    ("psychology", "expert", 0.9, "Broca's area in the brain is primarily involved in:",
     ["Speech production", "Visual processing", "Motor reflexes", "Hearing pitch"], 0,
     "Damage to Broca's area can cause difficulty producing fluent speech."),
    ("psychology", "easy", 0.25, "Short-term memory typically holds information for:",
     ["Milliseconds only", "Seconds to about a minute", "Several years", "A full lifetime"], 1,
     "Short-term memory retains limited information briefly without rehearsal."),
    ("psychology", "medium", 0.5, "The DSM is a manual used to classify:",
     ["Chemical elements", "Mental disorders", "Planetary orbits", "Economic indicators"], 1,
     "The Diagnostic and Statistical Manual defines criteria for mental health diagnoses."),
    ("psychology", "hard", 0.72, "Schizophrenia is characterized in part by:",
     ["Only physical paralysis", "Distorted thinking and perception", "Permanent blindness", "Bone density loss"], 1,
     "Schizophrenia involves symptoms such as hallucinations, delusions, and disorganized thinking."),
    ("psychology", "expert", 0.88, "Dual-process theory in psychology distinguishes:",
     ["Fast intuitive thinking and slow analytical thinking", "Left and right kidney function", "Day and night vision", "Hearing and smell only"], 0,
     "System 1 is automatic and fast; System 2 is deliberate and effortful."),

    # Finance
    ("finance", "easy", 0.3, "What does ROI stand for?",
     ["Rate of Interest", "Return on Investment", "Risk of Inflation", "Revenue on Income"], 1,
     "ROI means Return on Investment."),
    ("finance", "easy", 0.28, "Owning a share of stock represents:",
     ["A loan to the company", "Partial ownership in the company", "A government tax credit", "A fixed insurance policy"], 1,
     "Equity shares confer ownership stakes and often voting rights."),
    ("finance", "easy", 0.3, "A personal budget tracks:",
     ["Only vacation plans", "Income and expenses", "Weather forecasts", "Sports scores"], 1,
     "Budgets help manage cash flow by comparing earnings against spending."),
    ("finance", "medium", 0.5, "Inflation refers to a general increase in:",
     ["Employment only", "Prices of goods and services", "Land area", "Population density"], 1,
     "Inflation erodes purchasing power as the cost of living rises."),
    ("finance", "medium", 0.55, "Diversification in investing means:",
     ["Putting all money in one asset", "Spreading investments across different assets", "Avoiding all risk entirely", "Only buying cash"], 1,
     "Diversification reduces risk by not relying on a single investment's performance."),
    ("finance", "medium", 0.52, "GDP (Gross Domestic Product) measures:",
     ["Total value of goods and services produced in a country", "Number of banks only", "Average rainfall", "Military personnel count"], 0,
     "GDP is a broad indicator of national economic output."),
    ("finance", "hard", 0.75, "Compound interest differs from simple interest because it:",
     ["Never grows", "Earns interest on both principal and accumulated interest", "Only applies to loans under $100", "Eliminates all risk"], 1,
     "Compounding accelerates growth as interest itself earns future interest."),
    ("finance", "hard", 0.78, "A bear market typically describes:",
     ["A prolonged period of falling stock prices", "Rapid price increases only", "Stable zero volatility", "Government budget surpluses only"], 0,
     "Bear markets reflect widespread pessimism and declining asset values."),
    ("finance", "hard", 0.72, "Liquidity in finance refers to:",
     ["How easily an asset can be converted to cash", "How heavy gold bars are", "Permanent lock-in of funds", "Insurance deductibles"], 0,
     "Liquid assets can be sold quickly without significantly affecting price."),
    ("finance", "expert", 0.9, "The Black-Scholes model is used to price:",
     ["Real estate leases", "Stock options", "Agricultural crops", "Shipping containers"], 1,
     "Black-Scholes estimates fair values for European-style options."),
    ("finance", "expert", 0.88, "An inverted yield curve often signals:",
     ["Guaranteed economic boom", "Potential upcoming recession", "Zero inflation forever", "Rising commodity prices only"], 1,
     "When long-term yields fall below short-term yields, markets often anticipate slowdown."),
    ("finance", "medium", 0.5, "Corporate bonds are essentially:",
     ["Ownership shares in a company", "Debt securities issued by companies", "Government passports", "Physical warehouse receipts"], 1,
     "Bondholders lend money to corporations and receive periodic interest payments."),

    # Movies
    ("movies", "easy", 0.3, "Which film features the quote 'May the Force be with you'?",
     ["Star Trek", "Star Wars", "Dune", "Avatar"], 1,
     "The line is iconic to the Star Wars franchise."),
    ("movies", "easy", 0.28, "Who directed the film 'Titanic' (1997)?",
     ["Steven Spielberg", "James Cameron", "Christopher Nolan", "Quentin Tarantino"], 1,
     "James Cameron wrote and directed Titanic."),
    ("movies", "easy", 0.3, "The Lion King was produced by:",
     ["Pixar", "DreamWorks", "Disney", "Sony Pictures"], 2,
     "The Lion King is a Walt Disney Animation Studios film."),
    ("movies", "easy", 0.25, "Pixar's first feature film was:",
     ["Finding Nemo", "Toy Story", "Up", "Coco"], 1,
     "Toy Story (1995) was Pixar's groundbreaking first full-length CGI film."),
    ("movies", "medium", 0.5, "The Academy Awards are also known as:",
     ["The Emmys", "The Oscars", "The Grammys", "The Tonys"], 1,
     "The Oscars honor achievements in the film industry."),
    ("movies", "medium", 0.55, "The Marvel Cinematic Universe began its interconnected films prominently with:",
     ["Iron Man (2008)", "Superman (1978)", "Batman (1989)", "X-Men (2000)"], 0,
     "Iron Man launched the MCU's long-running shared universe strategy."),
    ("movies", "medium", 0.52, "The horror film 'Halloween' (1978) features the killer:",
     ["Freddy Krueger", "Michael Myers", "Jason Voorhees", "Pinhead"], 1,
     "John Carpenter's Halloween introduced Michael Myers as a masked killer."),
    ("movies", "hard", 0.75, "Citizen Kane (1941) was directed by:",
     ["Alfred Hitchcock", "Orson Welles", "Billy Wilder", "Frank Capra"], 1,
     "Orson Welles co-wrote, directed, and starred in Citizen Kane."),
    ("movies", "hard", 0.78, "The Godfather was directed by:",
     ["Martin Scorsese", "Francis Ford Coppola", "Stanley Kubrick", "Ridley Scott"], 1,
     "Coppola directed the acclaimed 1972 crime epic."),
    ("movies", "hard", 0.72, "Film noir is a style known for:",
     ["Bright musical comedy", "Dark, cynical crime dramas", "Animated fairy tales", "Nature documentaries"], 1,
     "Noir films often feature moral ambiguity, shadows, and crime themes."),
    ("movies", "expert", 0.9, "Akira Kurosawa's Rashomon is famous for its:",
     ["Single unchanging viewpoint", "Multiple conflicting accounts of one event", "Silent slapstick comedy", "Documentary footage only"], 1,
     "Rashomon explores truth and memory through contradictory witness narratives."),
    ("movies", "expert", 0.88, "Sergei Eisenstein pioneered editing techniques such as:",
     ["Montage", "Stop-motion clay animation", "3D IMAX capture", "Digital de-aging only"], 0,
     "Eisenstein used montage to create meaning through juxtaposed shots."),

    # Gaming
    ("gaming", "easy", 0.28, "In chess, which piece moves in an L-shape?",
     ["Bishop", "Rook", "Knight", "Queen"], 2,
     "The knight moves in an L-shape."),
    ("gaming", "medium", 0.55, "What does NPC commonly stand for in games?",
     ["New Player Character", "Non-Player Character", "Network Packet Code", "Next Phase Checkpoint"], 1,
     "NPC means Non-Player Character."),
    ("gaming", "easy", 0.25, "Mario is an iconic character created by:",
     ["Sega", "Nintendo", "Sony", "Microsoft"], 1,
     "Mario debuted in Nintendo's Donkey Kong and stars in many Nintendo games."),
    ("gaming", "easy", 0.3, "Pac-Man is a classic game from the:",
     ["Arcade era", "Virtual reality-only era", "Mobile-only era", "Cloud streaming-only era"], 0,
     "Pac-Man became a cultural phenomenon in early 1980s arcade gaming."),
    ("gaming", "medium", 0.5, "FPS in gaming stands for:",
     ["First-Person Shooter", "Fast Player Speed", "Final Phase Score", "Fixed Pixel Screen"], 0,
     "FPS games present action from the protagonist's point of view."),
    ("gaming", "medium", 0.55, "RPG stands for:",
     ["Random Player Generator", "Role-Playing Game", "Rapid Pixel Graphics", "Remote Play Gateway"], 1,
     "RPGs emphasize character development, story, and often stats-based progression."),
    ("gaming", "medium", 0.52, "An open-world game typically allows players to:",
     ["Explore freely with less linear restriction", "Only follow one fixed path", "Never save progress", "Play without graphics"], 0,
     "Open-world design emphasizes exploration across large environments."),
    ("gaming", "hard", 0.75, "A speedrun is when players attempt to:",
     ["Complete a game as slowly as possible", "Finish a game as fast as possible", "Never finish the game", "Only use cutscenes"], 1,
     "Speedrunners optimize routes and techniques to minimize completion time."),
    ("gaming", "hard", 0.78, "Esports refers to:",
     ["Competitive video gaming at professional levels", "Exercise gaming on treadmills only", "Board game conventions only", "Card shuffling techniques"], 0,
     "Esports features organized tournaments with skilled players and audiences."),
    ("gaming", "hard", 0.72, "Network lag in online gaming causes:",
     ["Instant victory", "Delayed response between player input and game reaction", "Permanent offline mode", "Automatic level ups"], 1,
     "High latency creates noticeable delay that affects competitive play."),
    ("gaming", "expert", 0.88, "Procedural generation in games creates content by:",
     ["Hand-drawing every asset manually", "Using algorithms to generate levels or items", "Deleting saved files randomly", "Recording live television"], 1,
     "Algorithms produce varied content such as maps, quests, or loot at runtime."),
    ("gaming", "easy", 0.28, "A game controller is primarily an:",
     ["Input device", "Output speaker", "Storage drive", "Cooling fan"], 0,
     "Controllers send player inputs like button presses and stick movements to the game."),

    # Sports
    ("sports", "easy", 0.25, "How many players are on the field for one soccer team during play?",
     ["9", "10", "11", "12"], 2,
     "A soccer team fields 11 players including the goalkeeper."),
    ("sports", "easy", 0.28, "A standard basketball team has how many players on the court?",
     ["4", "5", "6", "7"], 1,
     "Each basketball team plays five players on the court at a time."),
    ("sports", "easy", 0.3, "In baseball, hitting the ball out of the park in fair territory is a:",
     ["Single", "Double", "Home run", "Bunt"], 2,
     "A home run allows the batter to circle all bases and score."),
    ("sports", "medium", 0.5, "The Summer Olympics are typically held every:",
     ["2 years", "4 years", "6 years", "10 years"], 1,
     "The Olympic Games occur on a four-year cycle."),
    ("sports", "medium", 0.55, "Tennis has four Grand Slam tournaments, including:",
     ["Wimbledon", "The Super Bowl", "The Stanley Cup", "The Tour de France"], 0,
     "Wimbledon is one of tennis's four annual Grand Slam events."),
    ("sports", "medium", 0.52, "Formula One (F1) is a form of:",
     ["Open-wheel auto racing", "Ice hockey", "Marathon running", "Synchronized swimming"], 0,
     "F1 features single-seat open-cockpit cars racing on circuits worldwide."),
    ("sports", "hard", 0.75, "The offside rule in soccer prevents attackers from:",
     ["Scoring any goals", "Being nearer to the opponent's goal than the second-last defender when the ball is played to them", "Using their feet", "Playing in rain"], 1,
     "Offside restricts gaining an unfair advantage ahead of the ball and second-last defender."),
    ("sports", "hard", 0.78, "A marathon race is approximately:",
     ["13.1 miles", "20 miles", "26.2 miles", "31 miles"], 2,
     "The marathon distance is standardized at 26.2 miles (42.195 km)."),
    ("sports", "hard", 0.72, "In cricket, an 'over' consists of:",
     ["Six legal deliveries by one bowler", "Ten innings", "One hour of play", "Three wickets"], 0,
     "An over ends after six balls bowled by the same bowler from one end."),
    ("sports", "hard", 0.75, "The Triple Crown in horse racing traditionally refers to winning:",
     ["Three Olympic medals", "Three specific major races for three-year-olds", "Three consecutive Super Bowls", "Three tennis Grand Slams in one year"], 1,
     "In the US, it means winning the Kentucky Derby, Preakness, and Belmont Stakes."),
    ("sports", "expert", 0.9, "EPO (erythropoietin) abuse in sports is associated with:",
     ["Improved endurance through increased red blood cells", "Better eyesight only", "Reduced body weight instantly", "Faster bone healing always"], 0,
     "EPO stimulates red blood cell production, potentially boosting oxygen delivery."),
    ("sports", "expert", 0.88, "Sports biomechanics studies:",
     ["Only ticket pricing", "Mechanics of human movement in athletic performance", "Stadium architecture only", "Commentary scripts"], 1,
     "Biomechanics analyzes forces and motion to improve technique and reduce injury."),

    # Literature
    ("literature", "medium", 0.5, "Who wrote '1984'?",
     ["Aldous Huxley", "George Orwell", "Ray Bradbury", "Jules Verne"], 1,
     "George Orwell wrote Nineteen Eighty-Four."),
    ("literature", "easy", 0.28, "William Shakespeare wrote:",
     ["Romeo and Juliet", "The Odyssey", "Moby-Dick", "Pride and Prejudice"], 0,
     "Romeo and Juliet is one of Shakespeare's most famous tragedies."),
    ("literature", "easy", 0.3, "The Harry Potter book series was written by:",
     ["J.R.R. Tolkien", "J.K. Rowling", "C.S. Lewis", "Roald Dahl"], 1,
     "J.K. Rowling authored the seven main Harry Potter novels."),
    ("literature", "easy", 0.25, "A sonnet traditionally has how many lines?",
     ["10", "12", "14", "16"], 2,
     "The sonnet form typically consists of fourteen lines."),
    ("literature", "medium", 0.52, "Ernest Hemingway wrote 'The Old Man and the Sea'.",
     ["True", "False", "He only wrote poetry", "He co-wrote it with Dickens"], 0,
     "Hemingway published this novella in 1952."),
    ("literature", "medium", 0.55, "The Canterbury Tales was written by:",
     ["Geoffrey Chaucer", "John Milton", "Samuel Beckett", "Virginia Woolf"], 0,
     "Chaucer composed this collection of stories in Middle English."),
    ("literature", "medium", 0.5, "A dystopian novel typically depicts:",
     ["An ideal perfect society", "A frightening or oppressive society", "Only historical facts", "Cooking recipes"], 1,
     "Dystopias explore societal collapse, tyranny, or bleak futures."),
    ("literature", "hard", 0.75, "Homer's epic poem about Odysseus's journey is:",
     ["The Iliad", "The Odyssey", "Beowulf", "The Aeneid"], 1,
     "The Odyssey narrates Odysseus's long voyage home after the Trojan War."),
    ("literature", "hard", 0.78, "Franz Kafka's 'The Metamorphosis' begins with a man transforming into a:",
     ["Wolf", "Giant insect", "Tree", "Bird"], 1,
     "Gregor Samsa wakes to find himself changed into a monstrous vermin."),
    ("literature", "hard", 0.72, "The Beat Generation in American literature included writers such as:",
     ["Jack Kerouac", "Isaac Newton", "Galileo Galilei", "Napoleon Bonaparte"], 0,
     "Kerouac's On the Road epitomizes Beat literature's restless spirit."),
    ("literature", "expert", 0.9, "Stream of consciousness is a narrative technique associated with:",
     ["James Joyce", "Euclid", "Archimedes", "Ptolemy"], 0,
     "Joyce's Ulysses employs interior monologue to depict flowing thought."),
    ("literature", "expert", 0.88, "Magical realism often blends:",
     ["Only scientific formulas", "Realistic settings with fantastical elements", "Legal statutes with tax codes", "Sports statistics with weather data"], 1,
     "Authors like Gabriel García Márquez weave magic into otherwise realistic worlds."),

    # General Knowledge
    ("general-knowledge", "easy", 0.3, "How many continents are there on Earth?",
     ["5", "6", "7", "8"], 2,
     "The commonly taught model lists seven continents."),
    ("general-knowledge", "medium", 0.5, "What is H2O commonly known as?",
     ["Salt", "Water", "Oxygen", "Hydrogen peroxide"], 1,
     "H2O is the chemical formula for water."),
    ("general-knowledge", "easy", 0.28, "The capital of the United States is:",
     ["New York City", "Los Angeles", "Washington, D.C.", "Chicago"], 2,
     "Washington, D.C. is the federal capital of the United States."),
    ("general-knowledge", "easy", 0.25, "A red traffic light means:",
     ["Go", "Stop", "Speed up", "Turn only"], 1,
     "Red signals require vehicles to stop."),
    ("general-knowledge", "easy", 0.3, "A standard rainbow displays how many distinct color bands commonly taught?",
     ["5", "6", "7", "10"], 2,
     "The traditional sequence is red, orange, yellow, green, blue, indigo, violet."),
    ("general-knowledge", "medium", 0.52, "The United Nations (UN) is an organization focused on:",
     ["Only sports regulation", "International cooperation and peace", "Private banking only", "Local city zoning"], 1,
     "The UN promotes diplomacy, humanitarian aid, and global cooperation."),
    ("general-knowledge", "medium", 0.55, "Water freezes at 0°C on the:",
     ["Kelvin scale only", "Celsius scale", "Richter scale", "Beaufort scale"], 1,
     "On the Celsius scale, 0° marks the freezing point of water."),
    ("general-knowledge", "medium", 0.5, "NATO is primarily a:",
     ["Culinary alliance", "Military and political alliance", "Film awards body", "Oceanographic museum"], 1,
     "NATO (North Atlantic Treaty Organization) is a collective defense alliance."),
    ("general-knowledge", "hard", 0.75, "A leap year has how many days?",
     ["365", "366", "364", "367"], 1,
     "Leap years add February 29, giving 366 days."),
    ("general-knowledge", "hard", 0.78, "The Euro (€) is the currency used by many countries in:",
     ["South America", "The European Union", "Central Africa only", "Southeast Asia"], 1,
     "Multiple EU member states use the euro as their official currency."),
    ("general-knowledge", "hard", 0.72, "Guinness World Records documents:",
     ["Only Olympic scores", "Extreme human and world achievements", "Stock market prices daily", "Medical prescriptions"], 1,
     "Guinness catalogs verified records across countless categories."),
    ("general-knowledge", "expert", 0.88, "The Schengen Area in Europe primarily allows:",
     ["Free movement across internal borders without routine passport checks", "Mandatory military service for all tourists", "Ban on all air travel", "Single-language requirement by law"], 0,
     "Schengen members coordinate border policies to ease travel within the zone."),

    # Astronomy Expansion
    ("astronomy", "easy", 0.25, "Which planet is known as the Red Planet?",
     ["Venus", "Mars", "Jupiter", "Saturn"], 1,
     "Mars appears red due to iron oxide (rust) on its surface."),
    ("astronomy", "medium", 0.5, "What is the primary component of Saturn's rings?",
     ["Solid rock", "Water ice", "Gas clouds", "Liquid metallic hydrogen"], 1,
     "Saturn's rings consist mostly of water ice particles."),
    ("astronomy", "hard", 0.75, "What type of galaxy is the Milky Way?",
     ["Elliptical", "Barred spiral", "Irregular", "Lenticular"], 1,
     "The Milky Way is classified as a barred spiral galaxy."),
    ("astronomy", "expert", 0.9, "What is the estimated age of the observable universe?",
     ["4.5 billion years", "10 billion years", "13.8 billion years", "20 billion years"], 2,
     "Cosmological measurements place the universe's age at roughly 13.8 billion years."),
    ("astronomy", "medium", 0.55, "Which space telescope was launched in December 2021 as Hubble's successor?",
     ["James Webb Space Telescope", "Spitzer", "Chandra", "Kepler"], 0,
     "JWST was launched in late 2021 to observe the infrared universe."),
    ("astronomy", "easy", 0.3, "What natural satellite orbits the Earth?",
     ["Phobos", "The Moon", "Titan", "Io"], 1,
     "The Moon is Earth's only natural satellite."),
    ("astronomy", "hard", 0.8, "What is the solar wind comprised of?",
     ["Photons", "Charged particles (mostly protons and electrons)", "Dust particles", "Combustion gases"], 1,
     "The solar wind is a stream of plasma released from the Sun's atmosphere."),
    ("astronomy", "medium", 0.52, "Olympus Mons, the largest volcano in the solar system, is located on which planet?",
     ["Venus", "Mars", "Mercury", "Jupiter"], 1,
     "Olympus Mons is a massive shield volcano on Mars."),

    # Science Expansion
    ("science", "easy", 0.25, "What element does 'O' represent on the periodic table?",
     ["Osmium", "Oxygen", "Oganesson", "Oxalate"], 1,
     "O is the chemical symbol for oxygen."),
    ("science", "medium", 0.5, "What is the speed of sound in air at room temperature approximately?",
     ["343 m/s", "1500 m/s", "300,000 m/s", "30 m/s"], 0,
     "At 20°C, sound travels at roughly 343 meters per second in air."),
    ("science", "hard", 0.75, "What is absolute zero in Celsius?",
     ["-100°C", "-273.15°C", "-459.67°C", "0°C"], 1,
     "Absolute zero is 0 Kelvin or -273.15 degrees Celsius."),
    ("science", "expert", 0.9, "Which force mediates radioactive beta decay?",
     ["Gravitational force", "Electromagnetic force", "Weak nuclear force", "Strong nuclear force"], 2,
     "The weak force is responsible for subatomic beta decay."),

    # Physics Expansion
    ("physics", "medium", 0.55, "What law states that for every action there is an equal and opposite reaction?",
     ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", "Kepler's Second Law"], 2,
     "Newton's Third Law governs interaction forces between two bodies."),
    ("physics", "hard", 0.78, "What physical property remains constant in an ideal elastic collision?",
     ["Kinetic energy only", "Momentum only", "Both kinetic energy and momentum", "Velocity of each body"], 2,
     "Elastic collisions conserve both total kinetic energy and linear momentum."),
    ("physics", "easy", 0.28, "What device converts mechanical energy into electrical energy?",
     ["Motor", "Generator", "Transformer", "Capacitor"], 1,
     "Electric generators convert mechanical rotation into electricity."),

    # Chemistry & Biology Expansion
    ("chemistry", "easy", 0.25, "What is the common name for sodium chloride?",
     ["Sugar", "Table salt", "Baking soda", "Vinegar"], 1,
     "Sodium chloride (NaCl) is common table salt."),
    ("chemistry", "medium", 0.5, "Which particle is found in the nucleus of an atom alongside protons?",
     ["Electron", "Neutron", "Positron", "Photon"], 1,
     "Protons and neutrons form the atomic nucleus."),
    ("chemistry", "hard", 0.75, "What is the chemical formula of ozone?",
     ["O₂", "O₃", "H₂O₂", "CO₂"], 1,
     "Ozone is a triatomic molecule made of three oxygen atoms."),
    ("biology", "easy", 0.28, "What type of blood cells fight infections?",
     ["Red blood cells", "White blood cells", "Platelets", "Plasma"], 1,
     "White blood cells (leukocytes) protect the body against infectious disease."),
    ("biology", "medium", 0.52, "Where does protein synthesis occur inside a biological cell?",
     ["Nucleus", "Ribosomes", "Vacuoles", "Centrosomes"], 1,
     "Ribosomes translate mRNA into protein chains."),
    ("biology", "hard", 0.75, "What is the primary function of hemoglobin in red blood cells?",
     ["Digesting fats", "Carrying oxygen", "Pumping blood", "Filtering toxins"], 1,
     "Hemoglobin binds oxygen in the lungs and delivers it across tissues."),
    ("biology", "expert", 0.88, "Which hormone regulates blood sugar levels by facilitating glucose cellular intake?",
     ["Adrenaline", "Insulin", "Thyroxine", "Cortisol"], 1,
     "Insulin is secreted by the pancreas to lower blood glucose."),

    # Mathematics Expansion
    ("mathematics", "easy", 0.25, "What is the square root of 144?",
     ["10", "11", "12", "14"], 2,
     "12 × 12 = 144."),
    ("mathematics", "medium", 0.5, "In statistics, what is the median of the set [3, 7, 9, 12, 15]?",
     ["7", "9", "9.2", "12"], 1,
     "The middle number in an ordered odd-length set is 9."),

    # AI & Programming & Tech Expansion
    ("artificial-intelligence", "medium", 0.52, "What is a neural network activation function designed to introduce?",
     ["Linearly scaled weights", "Non-linearity", "Random noise", "Floating point errors"], 1,
     "Activation functions introduce non-linearities, allowing networks to learn complex patterns."),
    ("artificial-intelligence", "easy", 0.28, "What is supervised learning in AI?",
     ["Training with labeled input-output data", "Learning with zero data", "Running without CPU", "Training only on images"], 0,
     "Supervised learning relies on matched input data and target labels."),
    ("artificial-intelligence", "hard", 0.8, "What parameter in LLMs controls randomness in text generation?",
     ["Batch size", "Learning rate", "Temperature", "Context window"], 2,
     "Higher temperature increases randomness and creativity in model outputs."),
    ("programming", "easy", 0.25, "What is the index of the first element in a standard zero-indexed array?",
     ["1", "0", "-1", "2"], 1,
     "In zero-indexed languages, array indices start at 0."),
    ("programming", "medium", 0.5, "In object-oriented programming, what is encapsulation?",
     ["Bundling data and methods into a single unit/class", "Deleting unused variables", "Converting code to HTML", "Compiling twice"], 0,
     "Encapsulation hides internal details and exposes controlled interfaces."),
    ("programming", "hard", 0.75, "Which data structure operates on a Last-In, First-Out (LIFO) basis?",
     ["Queue", "Stack", "Array", "Linked list"], 1,
     "A stack accesses elements in LIFO order."),
    ("technology", "easy", 0.28, "What does IP stand for in IP address?",
     ["Internet Protocol", "Internal Process", "Interactive Program", "Integrated Power"], 0,
     "IP stands for Internet Protocol."),
    ("technology", "medium", 0.52, "What technology enables wireless short-range contactless payments?",
     ["NFC", "GPS", "5G", "VGA"], 0,
     "NFC (Near Field Communication) enables contactless payments."),
    ("technology", "hard", 0.78, "What is the primary function of a RAM cache in modern microprocessors?",
     ["Store permanent files", "Provide ultra-fast temporary access to frequently used data", "Manage network routing", "Render 3D graphics"], 1,
     "L1/L2/L3 caches store frequent instructions close to the CPU core."),

    # History & Geography Expansion
    ("history", "easy", 0.28, "Who painted the Mona Lisa?",
     ["Vincent van Gogh", "Leonardo da Vinci", "Pablo Picasso", "Claude Monet"], 1,
     "Leonardo da Vinci painted the Mona Lisa in the early 16th century."),
    ("history", "medium", 0.52, "Which empire built the Colosseum in Rome?",
     ["Greek Empire", "Roman Empire", "Ottoman Empire", "Byzantine Empire"], 1,
     "The Roman Empire constructed the Colosseum under the Flavian dynasty."),
    ("history", "hard", 0.75, "In which year did the American Civil War begin?",
     ["1776", "1812", "1861", "1914"], 2,
     "The American Civil War broke out in 1861."),
    ("geography", "easy", 0.25, "Which country has the largest land area in the world?",
     ["China", "Canada", "Russia", "United States"], 2,
     "Russia is the largest country by land area, spanning two continents."),
    ("geography", "medium", 0.5, "What is the longest river in South America?",
     ["Amazon River", "Nile River", "Mississippi River", "Yangtze River"], 0,
     "The Amazon is the longest and largest river by discharge volume in South America."),
    ("geography", "hard", 0.75, "Which African country is completely enclaved within South Africa?",
     ["Lesotho", "Eswatini", "Zimbabwe", "Namibia"], 0,
     "Lesotho is an independent kingdom surrounded entirely by South Africa."),

    # Psychology & Finance Expansion
    ("psychology", "easy", 0.28, "What is the term for an extreme, irrational fear of a specific object or situation?",
     ["Phobia", "Mania", "Amnesia", "Euphoria"], 0,
     "A phobia is an intense, persistent fear of a specific trigger."),
    ("psychology", "medium", 0.52, "Who is widely considered the founder of psychoanalysis?",
     ["Sigmund Freud", "Carl Rogers", "John B. Watson", "Jean Piaget"], 0,
     "Freud pioneered psychoanalytic theory and therapy."),
    ("finance", "easy", 0.28, "What is a central bank's primary tool for managing economic inflation?",
     ["Interest rates", "Printing coupons", "Taxing property", "Setting retail prices"], 0,
     "Central banks adjust benchmark interest rates to influence borrowing and inflation."),
    ("finance", "medium", 0.55, "What does a stock ticker symbol represent?",
     ["A short unique alphabetic code for a publicly traded company", "A bank account number", "A credit rating score", "A tax rate identifier"], 0,
     "Tickers (e.g. AAPL, GOOGL) uniquely identify stocks on exchanges."),

    # Movies, Gaming, Sports, Literature & General Knowledge Expansion
    ("movies", "easy", 0.28, "Which animated movie features the song 'Let It Go'?",
     ["Moana", "Tangled", "Frozen", "Brave"], 2,
     "Elsa sings 'Let It Go' in Disney's Frozen."),
    ("movies", "medium", 0.52, "Which actor played Iron Man / Tony Stark in the Marvel Cinematic Universe?",
     ["Chris Evans", "Robert Downey Jr.", "Chris Hemsworth", "Mark Ruffalo"], 1,
     "Robert Downey Jr. portrayed Tony Stark across 11 MCU films."),
    ("gaming", "easy", 0.25, "In Minecraft, what block type is required to build a Nether Portal frame?",
     ["Bedrock", "Obsidian", "Cobblestone", "Diamond Block"], 1,
     "Nether Portals are built using obsidian blocks ignited with flint and steel."),
    ("gaming", "medium", 0.52, "Which game studio developed 'The Witcher 3: Wild Hunt'?",
     ["Bethesda", "CD Projekt Red", "BioWare", "Ubisoft"], 1,
     "Polish studio CD Projekt Red created The Witcher 3."),
    ("sports", "easy", 0.28, "In golf, what is the term for scoring one under par on a single hole?",
     ["Eagle", "Birdie", "Bogey", "Albatross"], 1,
     "A birdie is a score of one stroke under par for a hole."),
    ("sports", "medium", 0.5, "How long is a standard professional soccer match excluding extra time?",
     ["80 minutes", "90 minutes", "100 minutes", "60 minutes"], 1,
     "Matches consist of two 45-minute halves totaling 90 minutes."),
    ("literature", "easy", 0.28, "Who wrote the play 'Hamlet'?",
     ["William Shakespeare", "Charles Dickens", "Mark Twain", "Jane Austen"], 0,
     "Shakespeare wrote the tragic play Hamlet around 1600."),
    ("literature", "medium", 0.52, "Which novel begins with 'Call me Ishmael'?",
     ["Moby-Dick", "Great Expectations", "To Kill a Mockingbird", "1984"], 0,
     "Herman Melville's Moby-Dick opens with this famous sentence."),
    ("general-knowledge", "easy", 0.25, "How many primary colors are in traditional color theory?",
     ["2", "3", "4", "5"], 1,
     "The three traditional primary colors are red, yellow, and blue."),
    ("general-knowledge", "medium", 0.5, "What is the capital city of France?",
     ["Lyon", "Marseille", "Paris", "Nice"], 2,
     "Paris is the capital and largest city of France."),
]


# Hindi starter bank.
#
# Small on purpose. Its job is to make Hindi playable the moment the app ships
# rather than after the first generation sweep completes — a language that is
# switchable but has nothing behind it reads as broken. The bank then grows the
# same way every other language does, through app.services.bank_inventory.
#
# Same tuple shape as BANK above: (topic_slug, difficulty_label, difficulty,
# prompt, options[4], correct_index, explanation).
HINDI_BANK: list[tuple] = [
    # --- सामान्य ज्ञान ---
    ("general-knowledge", "easy", 0.25, "भारत की राजधानी कौन सी है?",
     ["मुंबई", "कोलकाता", "नई दिल्ली", "चेन्नई"], 2,
     "नई दिल्ली भारत की राजधानी है और यहीं संसद तथा राष्ट्रपति भवन स्थित हैं।"),
    ("general-knowledge", "easy", 0.28, "एक वर्ष में कितने महीने होते हैं?",
     ["10", "11", "12", "13"], 2,
     "ग्रेगोरियन कैलेंडर में एक वर्ष बारह महीनों का होता है।"),
    ("general-knowledge", "medium", 0.5, "पानी का रासायनिक सूत्र क्या है?",
     ["CO2", "H2O", "O2", "NaCl"], 1,
     "पानी के एक अणु में दो हाइड्रोजन परमाणु और एक ऑक्सीजन परमाणु होते हैं, इसलिए इसका सूत्र H2O है।"),
    ("general-knowledge", "medium", 0.55, "भारत का राष्ट्रीय पक्षी कौन सा है?",
     ["कबूतर", "मोर", "तोता", "बाज"], 1,
     "मोर को 1963 में भारत का राष्ट्रीय पक्षी घोषित किया गया था।"),
    ("general-knowledge", "medium", 0.52, "इंद्रधनुष में परंपरागत रूप से कितने रंग गिने जाते हैं?",
     ["5", "6", "7", "9"], 2,
     "इंद्रधनुष के सात रंग माने जाते हैं — लाल, नारंगी, पीला, हरा, नीला, जामुनी और बैंगनी।"),
    ("general-knowledge", "hard", 0.72, "संयुक्त राष्ट्र संघ की स्थापना किस वर्ष हुई थी?",
     ["1919", "1945", "1950", "1962"], 1,
     "दूसरे विश्व युद्ध के बाद 1945 में संयुक्त राष्ट्र संघ की स्थापना हुई।"),

    # --- भारतीय इतिहास ---
    ("indian-history", "easy", 0.3, "भारत को स्वतंत्रता किस वर्ष मिली?",
     ["1942", "1945", "1947", "1950"], 2,
     "15 अगस्त 1947 को भारत ब्रिटिश शासन से स्वतंत्र हुआ।"),
    ("indian-history", "easy", 0.3, "भारत का संविधान किस वर्ष लागू हुआ?",
     ["1947", "1948", "1950", "1952"], 2,
     "26 जनवरी 1950 को भारत का संविधान लागू हुआ, इसीलिए यह दिन गणतंत्र दिवस है।"),
    ("indian-history", "medium", 0.5, "ताजमहल का निर्माण किस मुगल सम्राट ने करवाया था?",
     ["अकबर", "जहाँगीर", "शाहजहाँ", "औरंगज़ेब"], 2,
     "शाहजहाँ ने अपनी पत्नी मुमताज़ महल की स्मृति में आगरा में ताजमहल बनवाया।"),
    ("indian-history", "medium", 0.55, "भारत के पहले प्रधानमंत्री कौन थे?",
     ["सरदार पटेल", "जवाहरलाल नेहरू", "डॉ. राजेंद्र प्रसाद", "लाल बहादुर शास्त्री"], 1,
     "जवाहरलाल नेहरू 1947 में भारत के पहले प्रधानमंत्री बने।"),
    ("indian-history", "hard", 0.72, "मौर्य साम्राज्य की स्थापना किसने की थी?",
     ["अशोक", "चंद्रगुप्त मौर्य", "बिंबिसार", "समुद्रगुप्त"], 1,
     "चंद्रगुप्त मौर्य ने चाणक्य की सहायता से लगभग 322 ईसा पूर्व में मौर्य साम्राज्य की नींव रखी।"),
    ("indian-history", "hard", 0.75, "1857 के विद्रोह की शुरुआत किस छावनी से मानी जाती है?",
     ["कानपुर", "मेरठ", "झांसी", "लखनऊ"], 1,
     "10 मई 1857 को मेरठ छावनी में सिपाहियों के विद्रोह से इस संग्राम की शुरुआत हुई।"),

    # --- भूगोल ---
    ("geography", "easy", 0.28, "विश्व का सबसे बड़ा महासागर कौन सा है?",
     ["अटलांटिक महासागर", "हिंद महासागर", "प्रशांत महासागर", "आर्कटिक महासागर"], 2,
     "प्रशांत महासागर क्षेत्रफल और गहराई दोनों में सबसे बड़ा महासागर है।"),
    ("geography", "easy", 0.3, "भारत की सबसे लंबी नदी कौन सी है?",
     ["यमुना", "गोदावरी", "गंगा", "नर्मदा"], 2,
     "गंगा भारत में बहने वाली सबसे लंबी नदी है, जिसकी लंबाई लगभग 2,525 किलोमीटर है।"),
    ("geography", "medium", 0.5, "माउंट एवरेस्ट किस पर्वत श्रृंखला में स्थित है?",
     ["आल्प्स", "हिमालय", "एंडीज़", "अरावली"], 1,
     "माउंट एवरेस्ट हिमालय में नेपाल और चीन की सीमा पर स्थित है।"),
    ("geography", "medium", 0.55, "थार मरुस्थल मुख्य रूप से किस राज्य में फैला है?",
     ["गुजरात", "राजस्थान", "हरियाणा", "मध्य प्रदेश"], 1,
     "थार मरुस्थल का सबसे बड़ा भाग राजस्थान में है।"),
    ("geography", "medium", 0.52, "पृथ्वी की भूमध्य रेखा का अक्षांश कितना होता है?",
     ["0 डिग्री", "23.5 डिग्री", "45 डिग्री", "90 डिग्री"], 0,
     "भूमध्य रेखा 0 डिग्री अक्षांश पर है और पृथ्वी को उत्तरी व दक्षिणी गोलार्ध में बाँटती है।"),
    ("geography", "hard", 0.75, "क्षेत्रफल की दृष्टि से भारत का सबसे बड़ा राज्य कौन सा है?",
     ["मध्य प्रदेश", "महाराष्ट्र", "राजस्थान", "उत्तर प्रदेश"], 2,
     "क्षेत्रफल के हिसाब से राजस्थान भारत का सबसे बड़ा राज्य है।"),

    # --- विज्ञान ---
    ("science", "easy", 0.3, "पौधे प्रकाश संश्लेषण में कौन सी गैस लेते हैं?",
     ["ऑक्सीजन", "नाइट्रोजन", "कार्बन डाइऑक्साइड", "हाइड्रोजन"], 2,
     "पौधे कार्बन डाइऑक्साइड लेते हैं और ऑक्सीजन छोड़ते हैं।"),
    ("science", "easy", 0.28, "मानव शरीर का सबसे बड़ा अंग कौन सा है?",
     ["यकृत", "मस्तिष्क", "त्वचा", "फेफड़ा"], 2,
     "त्वचा पूरे शरीर को ढकती है और क्षेत्रफल के हिसाब से सबसे बड़ा अंग है।"),
    ("science", "medium", 0.5, "सोने का रासायनिक प्रतीक क्या है?",
     ["Go", "Gd", "Au", "Ag"], 2,
     "सोने का प्रतीक Au है, जो लैटिन शब्द 'ऑरम' से आया है।"),
    ("science", "medium", 0.55, "कोशिका का ऊर्जा गृह किसे कहा जाता है?",
     ["केंद्रक", "राइबोसोम", "माइटोकॉन्ड्रिया", "गॉल्जी काय"], 2,
     "माइटोकॉन्ड्रिया कोशिका की अधिकांश ऊर्जा (ATP) बनाते हैं, इसलिए इसे ऊर्जा गृह कहते हैं।"),
    ("science", "medium", 0.52, "समुद्र तल पर पानी कितने डिग्री सेल्सियस पर उबलता है?",
     ["90°C", "100°C", "110°C", "120°C"], 1,
     "सामान्य वायुमंडलीय दाब पर पानी 100°C पर उबलता है।"),
    ("science", "hard", 0.75, "ध्वनि किस माध्यम में सबसे तेज़ चलती है?",
     ["हवा", "पानी", "इस्पात", "निर्वात"], 2,
     "ध्वनि एक यांत्रिक तरंग है और घने, कठोर माध्यम जैसे इस्पात में सबसे तेज़ चलती है।"),

    # --- क्रिकेट ---
    ("cricket", "easy", 0.28, "एक ओवर में कितनी वैध गेंदें फेंकी जाती हैं?",
     ["4", "5", "6", "8"], 2,
     "एक ओवर में एक ही गेंदबाज़ द्वारा छह वैध गेंदें फेंकी जाती हैं।"),
    ("cricket", "easy", 0.3, "भारत ने पहली बार क्रिकेट विश्व कप किस वर्ष जीता?",
     ["1975", "1983", "1987", "1992"], 1,
     "कपिल देव की कप्तानी में भारत ने 1983 में पहला विश्व कप जीता था।"),
    ("cricket", "medium", 0.5, "टेस्ट क्रिकेट में एक पारी में अधिकतम कितने खिलाड़ी बल्लेबाज़ी करते हैं?",
     ["9", "10", "11", "12"], 2,
     "एक टीम में ग्यारह खिलाड़ी होते हैं, इसलिए एक पारी में अधिकतम ग्यारह बल्लेबाज़ आते हैं।"),
    ("cricket", "medium", 0.55, "अंतरराष्ट्रीय क्रिकेट में सर्वाधिक शतक किस भारतीय बल्लेबाज़ के नाम हैं?",
     ["विराट कोहली", "सचिन तेंदुलकर", "राहुल द्रविड़", "सुनील गावस्कर"], 1,
     "सचिन तेंदुलकर के नाम अंतरराष्ट्रीय क्रिकेट में 100 शतक दर्ज हैं।"),
    ("cricket", "medium", 0.52, "टी20 अंतरराष्ट्रीय मैच में प्रत्येक टीम कितने ओवर खेलती है?",
     ["10", "15", "20", "50"], 2,
     "टी20 प्रारूप में प्रत्येक टीम को बीस ओवर मिलते हैं।"),
    ("cricket", "hard", 0.72, "क्रिकेट में 'हैट्रिक' का क्या अर्थ है?",
     ["लगातार तीन गेंदों पर तीन विकेट", "एक ओवर में तीन छक्के",
      "तीन लगातार शतक", "तीन रन आउट"], 0,
     "जब कोई गेंदबाज़ लगातार तीन गेंदों पर तीन विकेट लेता है तो उसे हैट्रिक कहते हैं।"),
]


def _hash_question(
    topic_slug: str,
    prompt: str,
    options: list[str],
    language: str = DEFAULT_LANGUAGE.value,
) -> str:
    """Seed identity key, used to make re-seeding idempotent.

    The default language is deliberately *absent* from the hashed material:
    every English seed row already in a deployed database was hashed without
    it, and folding it in would make each of them look new and re-insert the
    whole bank on the next boot.
    """
    parts = [topic_slug]
    if language != DEFAULT_LANGUAGE.value:
        parts.append(language)
    parts.append(prompt.strip().lower())
    parts.extend(o.strip().lower() for o in options)
    return sha256("|".join(parts).encode("utf-8")).hexdigest()


async def _insert_bank(
    db,
    topics: dict,
    bank: list[tuple],
    language: str,
    touched_topic_ids: set,
) -> int:
    """Insert every unseen row of one language's bank. Returns how many landed."""
    inserted = 0
    for topic_slug, diff_label, diff_value, prompt, options, correct, explanation in bank:
        topic = topics.get(topic_slug)
        if not topic:
            continue
        content_hash = _hash_question(topic_slug, prompt, options, language)
        already = await db.scalar(select(Question.id).where(Question.content_hash == content_hash))
        if already:
            continue
        q = Question(
            topic_id=topic.id,
            prompt=prompt,
            explanation=explanation,
            language=language,
            source="curated_seed",
            difficulty=diff_value,
            difficulty_label=DifficultyLabel(diff_label),
            correct_option_index=correct,
            quality_score=92,
            status=QuestionStatus.ACTIVE,
            content_hash=content_hash,
            generation_meta={"seed": True, "language": language},
        )
        db.add(q)
        await db.flush()
        for i, text in enumerate(options):
            db.add(QuestionOption(question_id=q.id, position=i, text=text))
        topic.question_count = (topic.question_count or 0) + 1
        touched_topic_ids.add(topic.id)
        inserted += 1
    return inserted


async def seed_question_bank() -> None:
    async with session_scope() as db:
        topics = {
            t.slug: t
            for t in (await db.execute(select(Topic))).scalars().all()
        }
        touched_topic_ids: set = set()
        inserted = 0
        for language, bank in (
            (DEFAULT_LANGUAGE.value, BANK),
            (ContentLanguage.HINDI.value, HINDI_BANK),
        ):
            inserted += await _insert_bank(db, topics, bank, language, touched_topic_ids)

        for topic_id in touched_topic_ids:
            topic = next(t for t in topics.values() if t.id == topic_id)
            count = await db.scalar(
                select(func.count())
                .select_from(Question)
                .where(
                    Question.topic_id == topic_id,
                    Question.status == QuestionStatus.ACTIVE,
                )
            )
            topic.question_count = count or 0

        # Keep catalog counts honest even when nothing new was inserted.
        if inserted == 0:
            for topic in topics.values():
                if topic.is_custom:
                    continue
                count = await db.scalar(
                    select(func.count())
                    .select_from(Question)
                    .where(
                        Question.topic_id == topic.id,
                        Question.status == QuestionStatus.ACTIVE,
                    )
                )
                topic.question_count = count or 0

        logger.info("question_bank_seeded", inserted=inserted)
